### ISSUE TITLE
Routing to LLMs

### ISSUE THREAD

**Issue by ryderwishart** [dadukhankevin/SmartFunctions#1]
Seems like some overlap? https://github.com/andrewnguonly/ChatAbstractions?tab=readme-ov-file#chatnotdiamond

**Comment by dadukhankevin** [comment]
@ryderwishart Thanks, looks like an interesting project!
There's some overlap, but not a lot? (I haven't had time to test it yet)
It seems like ChatAbstractions is meant as a way of routing queries to the appropriate LLM based on prompt complexity or other criteria:
```
"ChatNotDiamond
The implementation of ChatNotDiamond demonstrates
the ability leverage 
[Not Diamond's](https://www.notdiamond.ai/) optimized LLM routing functionality."
```
[source: ChatAbstractions](https://github.com/andrewnguonly/ChatAbstractions?tab=readme-ov-file#chatnotdiamond)
If I understand correctly, it routes a query to the LLM most capable of answering it, whereas SmartFunctions routes queries to functions, and then uses an LLM to fill the parameters appropriately. I suppose you could use SmartFunctions in this way, but I haven't tried it. Definitely could be useful though! Seems like maybe a meta mixture of experts setup, especially if you look at the [Not Diamond front page](https://www.notdiamond.ai/).
